### ISSUE TITLE
MySQL 5.6 - MyISAM - Cannot start DB

### ISSUE THREAD

**Issue by craigwillis85** [lando/mysql#20]
Hi

I have a fairly old application that I want to get setup on Lando. It runs PHP 5.6, which is fine, but also runs MySQL 5.6

The issue is, it uses the MyISAM engine for the DB and I'm struggling to get this working.

I have the following in my `lando.yml`

    database:
        overrides:
          image: mysql:5.6

This seems to pull the image down, but i see the dreaded `Waiting until database service is ready...` repeated for a while, then lando starts, but the DB hasn't started.

The logs just say

    database_1   | /entrypoint.sh: line 28: /run.sh: No such file or directory
    proj_database_1 exited with code 1

Any ideas as to why or how to get MySQL5.6 running?

Thanks

**Comment by reynoldsalec** [comment]
If you're using a custom database image (in this case the core Docker Hub MySQL image), you'd probably need to provide some further instructions to get it going. I'm guessing assigning the MySQL images default entrypoint would get you further:

```
services:
  database:
    overrides:
      image: mysql
      command: docker-entrypoint.sh mysqld
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_DATABASE: mysql,
        MYSQL_PASSWORD: mysql,
        MYSQL_USER: mysql,
```

...you'd also need to set some volumes to have data persist and other fun stuff.

See [docs on overriding services](https://docs.lando.dev/core/v3/lando-service.html#overrides) for more details and a helpful [example of a MariaDB service](https://github.com/lando/pantheon/blob/main/services/pantheon-mariadb/builder.js#L43-L66) being built from the official Docker Hub image on the Pantheon recipe. This is also something that folks on the Lando Slack can help with.

Note that using custom images will get MUCH easier in Lando 4, and that official Docker images will be the default for Lando 4 services. Ah that sweet tomorrow just over the horizon...
