### ISSUE TITLE
MYSQL error

### ISSUE THREAD

**Issue by aksld** [lando/mysql#3]
Hello,

I have the following error when trying to use mysql container :

Error: Failed to get current SQL modes. Reason: Info: Using unique option prefix 'pass' is error-prone and can break in the future. Please use the full name 'password' instead.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by reynoldsalec** [comment]
I'm going to close this out since it's been a few weeks, but definitely let us know if you have further info. The Lando Slack is probably the best place to go, since this sounds like a one-off specific to your use case: https://launchpass.com/devwithlando
