### ISSUE TITLE
Mysql won't start after upgrading to Lando 3.20.6 on MacBook Pro M1

### ISSUE THREAD

**Issue by rob-zivtech** [lando/mysql#37]
recipe: drupal10

**Comment by reynoldsalec** [comment]
I haven't had an issue with running MySQL on ARM Mac, but a couple things to check if others are having issues.

- Make sure your Docker Desktop is up-to-date.
- Try running with the "Use Rosetta for x86/amd64 emulation on Apple Silicon" setting in Docker Desktop

If all else fails, check the error logs on the container in Docker Desktop and reopen this ticket with the output, will be interested to take a look!
